### ISSUE TITLE
Negative Starting Skills

### ISSUE THREAD

**Issue by bathoz** [ForgottenGlory/Dungeons-Deviousness#11]
**D&D Version**
Alpha 5

**Describe the bug**
After choosing a choosing starting class/birthsign, any skills that are not "class skills" appear to be reduced by 10. These skills don't appear to increase during play.

**To Reproduce**
Create character, choose attributes, setup MCM per guide. Equip weapon, choose class, choose starsign (third age).

**Expected behavior**
Stats not being reduced to -5.

**Screenshots**
Pre Choosing Class
![ScreenShot283](https://user-images.githubusercontent.com/69322356/89677920-8d243d80-d8ee-11ea-95a0-b9066e1d5dbc.png)
Post Choosing Class
![ScreenShot284](https://user-images.githubusercontent.com/69322356/89677887-7da4f480-d8ee-11ea-97e5-0fa7df526af3.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
So, I'm torn on this. One one hand, it kinda fits that you're locked into the skills your class gives you. On the other, I get that people want to diversify. I'm open to discussion on this.

**Comment by Sinful-Soles** [comment]
After playing a bit I think the best compromise could be to see if it's possible to limit the cap on the skills not in your class? So the main skills go to the max, but the other might only cap to a maximum? Otherwise this really does limit some nice things you might like, as I know some warriors do like to enchant their own things, or me as a paladin is is very limited as I need some restoration and a few magic spells to play how I want.

**Comment by ForgottenGlory** [comment]
As a compromise I've decided that skills starting at 0 is acceptable - you can still level them up (negative skills can't level up from what I can tell) but you'll be significantly behind on them compared to your class's skills. Fixed Pre-release build 1
