### ISSUE TITLE
Breast Physic is acting strange

### ISSUE THREAD

**Issue by Kukoro** [ForgottenGlory/Dungeons-Deviousness#18]
**D&D Version**
6.0

**Describe the bug**
Breast Physic is acting strange

**To Reproduce**
Walk a bit

**Expected behavior**
Breasts shouldn't act on their own

**Screenshots**
![image](https://user-images.githubusercontent.com/19671583/89937105-efde4780-dc14-11ea-8a78-bb52cc2091cb.png)

**Additional context**
This suggestion fixed the issue:
![image](https://user-images.githubusercontent.com/19671583/89937344-43509580-dc15-11ea-807a-90ef8a7d2102.png)

I used the D&D Prebuilt Bodyslides and only added this face-preset
![image](https://user-images.githubusercontent.com/19671583/89937070-e6ed7600-dc14-11ea-9a4c-12c413b97bb2.png)

**Comment by ForgottenGlory** [comment]
Fixed Alpha 7

**Comment by GesOka** [comment]
The issue do not seems to be fixed in Alpha 7.
This is happening only when you wear clothes. Naked body is OK.

![Annotation 2020-08-25 165511](https://user-images.githubusercontent.com/70215743/91190346-c5e85300-e6f3-11ea-872c-c330071187fb.jpg)

I tried what was suggested (re-install CBBE 3BBB) but the result is the same.
